spring:
  application:
    name: batch-government-general
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danal_restaurant_info?characterEncoding=utf8&autoReconnect=true
    username: root
    password: 3478
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    database: mysql
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.querydsl.sql: DEBUG